In [2]:
from pathlib import Path
import sys

PROJECT_ROOT = Path("~/UNSW-MRes/MRes/seacofs_eddy_dataset_modular").expanduser()

SRC = PROJECT_ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from seacofs_eddy_dataset.config import load_config

CONFIG_PATH = PROJECT_ROOT / "config" / "local.yaml"
config = load_config(CONFIG_PATH)

In [3]:
# import pandas as pd

# df_eddies = pd.read_parquet(
#     config.output_root / "processed" / "eddy_dataset_processed.parquet"
# )

# df_eddies.head()

Empty DataFrame
Columns: [Day, fnumber, nxc, nyc, nCyc, nic, njc, xc, yc, w, q11, q12, q22, Omega0, Omega, Rc, psi0, R, err, Omega0_abs]
Index: []

In [9]:
import pandas as pd

df_eddies = pd.read_parquet(
    config.output_root / "detections" / "fnumber=01461.parquet"
)

# df_eddies.head()
df_eddies

       Day    nxc     nyc Cyc  nic  njc  fnumber
0     1462  830.0  1515.0  AE  245  307     1461
1     1462  358.0  1408.0  AE  136  285     1461
2     1462  928.0  1356.0  CE  261  274     1461
3     1462  506.0  1354.0  CE  179  274     1461
4     1462  754.0  1285.0  AE  231  260     1461
...    ...    ...     ...  ..  ...  ...      ...
1138  1491  640.0   109.0  AE  209   22     1461
1139  1491  567.0   106.0  CE  193   22     1461
1140  1491  979.0   101.0  CE  269   20     1461
1141  1491  286.0    53.0  AE  109   11     1461
1142  1491  318.0     7.0  CE  122    1     1461

[1143 rows x 7 columns]

In [10]:
import pandas as pd

df_eddies = pd.read_parquet(
    config.output_root / "surface_eddies" / "fnumber=01461.parquet"
)

# df_eddies.head()
df_eddies

,Day,fnumber,nxc,nyc,nCyc,nic,njc,xc,yc,w,q11,q12,q22,Omega0,Omega,Rc,psi0,R
0,1462,1461,830.0,1515.0,AE,245,307,829.879126,1515.297884,0.015631,0.705472,-0.172995,1.459911,0.007219,0.008484,93.406313,-37.010850,63.384028
1,1462,1461,358.0,1408.0,AE,136,285,357.902634,1407.794571,0.031539,1.252542,-0.373183,0.909563,0.014587,0.013593,77.893592,-41.235849,50.068171
2,1462,1461,928.0,1356.0,CE,261,274,928.181752,1356.070550,-0.010848,0.918433,-0.656814,1.558529,-0.004380,-0.007231,108.660559,42.689603,74.597458
3,1462,1461,506.0,1354.0,CE,179,274,505.750855,1353.499933,-0.032406,1.091520,-0.174833,0.944157,-0.015919,-0.013597,103.202167,72.408844,69.457705
4,1462,1461,754.0,1285.0,AE,231,260,753.849693,1284.689807,0.022045,1.300245,-0.375378,0.877456,0.010123,0.009263,91.462547,-38.743359,65.961546
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1138,1491,1461,640.0,109.0,AE,209,22,639.134161,108.267697,0.021046,1.098562,0.006985,0.910326,0.010477,0.010984,38.514888,-8.146773,23.330094
1139,1491,1461,567.0,106.0,CE,193,22,566.957665,105.202836,-0.005135,0.963795,0.175698,1.069595,-0.002526,-0.004302,78.126803,13.128476,33.836477
1140,1491,1461,979.0,101.0,CE,269,20,985.460617,99.698380,-0.007437,0.549499,0.558803,2.388103,-0.002532,-0.001919,88.878491,7.581147,51.345086
1141,1491,1461,286.0,53.0,AE,109,11,285.835705,53.432840,0.029722,1.075314,0.222878,0.976157,0.014488,0.012815,63.229667,-25.616742,34.797473
1142,1491,1461,318.0,7.0,CE,122,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
import pandas as pd

df_eddies = pd.read_parquet(
    config.output_root / "tracked" / "eddy_tracks.parquet"
)

# df_eddies.head()
df_eddies

Empty DataFrame
Columns: [Day, fnumber, nxc, nyc, nCyc, nic, njc, xc, yc, w, q11, q12, q22, Omega0, Omega, Rc, psi0, R, err, Omega0_abs]
Index: []